### ISSUE TITLE
Atualizando para Java 11

### ISSUE THREAD

**Issue by evelinamorim** [cogroo/cogroo4#28]
Ao usar a biblioteca versão 4.3.1, com o maven e Java 11, o seguinte erro ocorre:

```
Caused by: javax.xml.bind.JAXBException: Provider com.sun.xml.internal.bind.v2.ContextFactory not found
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:149)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:362)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:446)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:409)
	at org.cogroo.config.LanguageConfigurationUtil.unmarshal(LanguageConfigurationUtil.java:101)
	at org.cogroo.config.LanguageConfigurationUtil.get(LanguageConfigurationUtil.java:71)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:578)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:146)
	... 13 more
```

Acredito que seja por que o jaxb não está mais disponível de forma embutida a partir do Java 9.

**Comment by rafaelanchieta** [comment]
Se ainda tiver interesse e não tiver resolvido esse problema, basta adicionar as seguintes dependências.

```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>

<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.1</version>
    <scope>runtime</scope>
</dependency>

```

**Comment by michelole** [comment]
Olá pessoal, obrigado pelo feedback! Vocês poderiam preparar um PR?
